name: Hello World

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
    - name: Say Hello
      run: |
        echo "Hello World!"
        echo This workflow was triggered by: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}""